### ISSUE TITLE
Question regarding number of macros in ws_dummy_buffer_many_macro

### ISSUE THREAD

**Issue by Farbin** [mit-emze/cimloop#4]
Hi! Could you kindly answer these two questions?

1. For ws_dummy_buffer_many_macro, there is a fixed number of 4096 macros. What happens to the unused macros? Won’t they draw leakage energy?   

2. How can we set the number of macros based on the weight size of the full model in CiMLoop?

Thanks!

**Comment by tanner-andrulis** [comment]
- The default run_layer function sets "has_power_gating" to True for the macro, which lets the unused macros be power gated when unused to avoid leakage power. You may turn this setting off to measure their leakage. In general, when running designs, I set has_power_gating to True for tiles to let each tile be independently power gated if unused.

- There's currently no way to set the number of macros based on the weight tensor sizes automatically. I have a few ideas, however. You may try:
  - Writing a script that calculates weight tensor sizes using TimeloopFE processors (examples in the timeloop-accelergy-exercises repo) and use that to calculate the number of macros required.
  - Continue using a great many macros, but edit the 'spatial_map_all_weights' definition to avoid replication of weights (those PQ and N lines in its definition.) To force no weight replication, you can add a 'must_iterate_over_dataspaces: '[Weights]' constraint to all spatial fanouts. When you do this, the architecture should be constrained to use the minimal number of macros possible, so you can see your macro count by looking at how many are utilized in the mapping.

**Comment by Farbin** [comment]
Thank you very much for your reply Tanner. I think I can use the last option you said. Just to verify, is this the right way to force the minimal number of macro usage?

<img width="576" alt="image" src="https://github.com/user-attachments/assets/551cb4dc-ab87-4e8a-9cd4-398728b2597f">

And is the right way to find out how many macros were utilized is to look at the ```Utilized instances (max)``` number in the row drivers OR column drivers? For example, if my macro size is ```rxc```, then ```ceil(row drivers utilized instances (max) / r)``` would be the. number of used macros?

**Comment by tanner-andrulis** [comment]
That is the correct way to set the minimal number of instances.

As for your second question, I'm not sure where these parameters would be coming from. What is rxc ? You can also look at the mapping to derive the number of utilized instances pretty easily.

**Comment by Farbin** [comment]
Thanks so much!
About the second question, this is the mapping I get for the second convolution layer in vgg16 with 32x32 macro size.
Does it mean: 3 x 3 x 2 x 2 = 36 macros are used?
<img width="556" alt="image" src="https://github.com/user-attachments/assets/aebe5090-84fe-4c93-bc77-9406013bef38">

**Comment by tanner-andrulis** [comment]
Yes, yes it does!

**Comment by Farbin** [comment]
Thank you very much! I really appreciate your help!
