### ISSUE TITLE
About center_entries and debugging method

### ISSUE THREAD

**Issue by shhj9787** [mit-emze/cimloop#7]
In RAELLA's macro, it seems that the center_entries in output_center_offset_correct exist as much as ARRAY_PARALLEL_OUTPUT(= the number of columns). Why do they exist per column rather than per grouped column?

And also,  I'm curious if there is a way to directly debug or check the calculation process through Python or C++ code instead of using the YAML file in the energy measurement process.

Thanks!

**Comment by tanner-andrulis** [comment]
Thank you for the question!

- If the number of `center_entries` is equal to the number of columns, that is almost certainly a bug and I'll look into it. There should be (# Columns per array) / (# Columns per weight) center entries.
- To debug with a debugger, you can look at the outputs in the outputs directory. There are files called `parsed_processed_input.yaml` that store an intermediate of the input file, and these can be called directly through the `accelergy` or `timeloop-mapper` executables. Attaching GDB to these executables & calling them on the YAML file should allow you to hook into these executables. Note that Accelergy uses a large suite of plug-ins, and Timeloop is a very large and complex codebase. Debugging in this way will be a challenge. You may also look at the log files or call `accelergy --verbose` on the input files, which would give you more information without going through the debugger.

**Comment by shhj9787** [comment]
Thanks for your response!

**Comment by tanner-andrulis** [comment]
Fixed `center_entries` in the latest commit-- thank you!
